/**
 * Per-section markdown renderers.
 *
 * Each function returns a markdown string for one section of the
 * canonical schema (see `docs/schema/workbook-model.md`).
 *
 * Sections always include the H2 heading and the YAML block, even
 * when the underlying data is empty — empty sections render as
 * `[]` rather than being silently dropped.
 */

import type {
  Action,
  Calculation,
  Dashboard,
  DataSource,
  Field,
  Filter,
  Parameter,
  TableauWorkbook,
  VisualEncoding,
  Worksheet,
  WorkbookMetadata,
} from '../../parsers/model.js';
import { toYamlReady, yamlBlock } from './yaml-block.js';

export function renderHeader(workbook: TableauWorkbook): string {
  const { metadata } = workbook;
  return [
    `# Workbook Model: ${metadata.name}`,
    '',
    `> Generated by [keptr](https://github.com/raguvindtharanitharan/keplr) from \`${metadata.originalFilename}\` on ${metadata.exportedAt}.`,
    '',
  ].join('\n');
}

export function renderMetadataSection(metadata: WorkbookMetadata): string {
  return section('Metadata', undefined, yamlBlock({ workbook: toYamlReady(metadata) }));
}

export function renderExecutiveSummary(summary: string | undefined): string {
  const body = summary && summary.trim().length > 0 ? summary.trim() : '_(not provided)_';
  return [
    '## Executive Summary',
    '',
    '> A high-level, natural-language description of what this workbook shows. Optional in v0.1; can be written by hand or auto-generated later.',
    '',
    body,
    '',
  ].join('\n');
}

export function renderDataSources(dataSources: DataSource[]): string {
  return section(
    'Data Sources',
    undefined,
    yamlBlock({ data_sources: toYamlReady(dataSources) })
  );
}

export function renderFields(fields: Field[]): string {
  return section(
    'Fields & Semantic Layer',
    'Captures the business meaning of every field across all data sources.',
    yamlBlock({ fields: toYamlReady(fields) })
  );
}

export function renderWorksheets(worksheets: Worksheet[]): string {
  return section(
    'Worksheets',
    'Basic information about each worksheet. Detailed visual configuration lives in the Visual Encodings section.',
    yamlBlock({ worksheets: toYamlReady(worksheets) })
  );
}

export function renderVisualEncodings(encodings: VisualEncoding[]): string {
  return section(
    'Visual Encodings',
    'How each worksheet maps fields onto its mark and shelves. The richest section in the model — drives code generation in v0.2.',
    yamlBlock({ visual_encodings: toYamlReady(encodings) })
  );
}

export function renderDashboards(dashboards: Dashboard[]): string {
  return section(
    'Dashboards & Layout',
    "Dashboard composition with the full layout zone tree preserved for v0.3's React-grid reconstruction.",
    yamlBlock({ dashboards: toYamlReady(dashboards) })
  );
}

export function renderFiltersParametersActions(
  filters: Filter[],
  parameters: Parameter[],
  actions: Action[]
): string {
  const blocks = [
    yamlBlock({ filters: toYamlReady(filters) }),
    yamlBlock({ parameters: toYamlReady(parameters) }),
    yamlBlock({ actions: toYamlReady(actions) }),
  ].join('\n\n');
  return section('Filters, Parameters & User Controls', undefined, blocks);
}

export function renderCalculations(calcs: Calculation[]): string {
  return section(
    'Calculations & Business Logic',
    'Calculated fields with their Tableau formulas captured verbatim. Dependency analysis (`depends_on`) lands in v0.2+.',
    yamlBlock({ calculations: toYamlReady(calcs) })
  );
}

export function renderNotes(notes: string[]): string {
  return section(
    'Additional Context & Notes',
    'Open section for anything that helps an AI agent or human understand the workbook in depth.',
    yamlBlock({ notes: toYamlReady(notes) })
  );
}

function section(heading: string, narrative: string | undefined, body: string): string {
  const lines = [`## ${heading}`, ''];
  if (narrative) {
    lines.push(narrative, '');
  }
  lines.push(body, '');
  return lines.join('\n');
}
